export const sampleFavs = [
    { postId: "Post ID 1", content: "Sample Content 1", waterLevel: "Normal" },
    { postId: "Post ID 2", content: "Sample Content 2", waterLevel: "High" },
    { postId: "Post ID 3", content: "Sample Content 3", waterLevel: "Low" },
    { postId: "Post ID 4", content: "Sample Content 4", waterLevel: "Normal" },
    { postId: "Post ID 5", content: "Sample Content 5", waterLevel: "High"},
    { postId: "Post ID 6", content: "Sample Content 6", waterLevel: "Low" },
    { postId: "Post ID 7", content: "Sample Content 7", waterLevel: "Normal" },
    { postId: "Post ID 8", content: "Sample Content 8", waterLevel: "High" },
    { postId: "Post ID 9", content: "Sample Content 9", waterLevel: "Low" },
    { postId: "Post ID 10", content: "Sample Content 10", waterLevel: "Normal"},
    { postId: "Post ID 1", content: "Sample Content 1", waterLevel: "Normal" },
    { postId: "Post ID 2", content: "Sample Content 2", waterLevel: "High" },
    { postId: "Post ID 3", content: "Sample Content 3", waterLevel: "Low" },
    { postId: "Post ID 4", content: "Sample Content 4", waterLevel: "Normal" },
    { postId: "Post ID 5", content: "Sample Content 5", waterLevel: "High"},
    { postId: "Post ID 6", content: "Sample Content 6", waterLevel: "Low" },
    { postId: "Post ID 7", content: "Sample Content 7", waterLevel: "Normal" },
    { postId: "Post ID 8", content: "Sample Content 8", waterLevel: "High" },
    { postId: "Post ID 9", content: "Sample Content 9", waterLevel: "Low" },
    { postId: "Post ID 10", content: "Sample Content 10", waterLevel: "Normal"},{ postId: "Post ID 1", content: "Sample Content 1", waterLevel: "Normal" },
    { postId: "Post ID 2", content: "Sample Content 2", waterLevel: "High" },
    { postId: "Post ID 3", content: "Sample Content 3", waterLevel: "Low" },
    { postId: "Post ID 4", content: "Sample Content 4", waterLevel: "Normal" },
    { postId: "Post ID 5", content: "Sample Content 5", waterLevel: "High"},
    { postId: "Post ID 6", content: "Sample Content 6", waterLevel: "Low" },
    { postId: "Post ID 7", content: "Sample Content 7", waterLevel: "Normal" },
    { postId: "Post ID 8", content: "Sample Content 8", waterLevel: "High" },
    { postId: "Post ID 9", content: "Sample Content 9", waterLevel: "Low" },
    { postId: "Post ID 10", content: "Sample Content 10", waterLevel: "Normal"},
    // ... more sample data
  ];
  